name: at_dude
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: ">=2.12.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  at_client_mobile: ^3.1.17
  at_utils: ^3.0.10
  path_provider: ^2.0.5
  flutter_dotenv: ^5.0.2
  at_app_flutter: ^5.0.1
  at_onboarding_flutter: ^5.0.0
  provider: ^6.0.3
  at_contacts_flutter: ^4.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

