name: at_rpc_demo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  at_client: ^3.0.69
  at_cli_commons: ^1.0.4
  chalkdart: ^2.0.9
  math_expressions: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
