name: at_rpc_demo
description: Sample client and server programs demonstrating use of the at_client package's AtRpc library
version: 1.1.0
publish_to: none

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  at_client: ^3.0.69
  at_cli_commons: ^1.0.4
  chalkdart: ^2.0.9
  math_expressions: ^2.4.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
